# Docker
docker-hub-email: smallaiah16@gmail.com
docker-hub-username: cicdadmin
docker-hub-password: Blueshirt@123
docker-hub-repo-name: jmkarthik/concourse-kubectl-resource

# Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8 TOKEN>>
